//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogLevelWF_MVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Aggregate_ID { get; set; }
    
        public virtual Aggregate Aggregate { get; set; }
    }
}
